apiVersion: v1
kind: ReplicationController
metadata:
  name: flask-app-replication-controller
spec:
  replicas: 3
  selector:
    app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: gateteyvan/flask_todo_app:latest2
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_HOST
          value: "mongo-service"
        - name: MONGO_PORT
          value: "27017"
